name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  image: 'docker://rtcamp/action-slack-notify:v2.0.3'
branding:
  icon: 'bell'
  color: 'yellow'
