name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
runs:
  using: 'docker'
#  image: 'docker://rtcamp/action-slack-notify:v2.1.0'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
